# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_description_short',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='job_posting',
            name='job_description_short',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='musician_advertisement',
            name='ad_description_short',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
