# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_application_application_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='EventApplication',
        ),
    ]
