# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_adapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adapplication',
            old_name='user',
            new_name='user_who_applied',
        ),
    ]
