# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_auto_20161204_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adapplication',
            old_name='application_ad',
            new_name='ad_name',
        ),
    ]
