# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_auto_20161204_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician_advertisement',
            name='ad_application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.AdApplication'),
        ),
    ]
