# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_musician_advertisement_ad_application'),
        ('board', '0018_event_event_address'),
    ]

    operations = [
    ]
