# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_merge_20161204_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.EventApplication'),
        ),
    ]
