# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_auto_20161204_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_lat',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_long',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
