# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20161204_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='soundcloud_username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
