# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20161205_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
