# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20161205_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address_lat',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_long',
        ),
    ]
