# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 02:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_user', models.CharField(choices=[(b'Musician', b'Musician'), (b'Venue', b'Venue')], default=b'Musician', max_length=20)),
                ('location', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True, max_length=400)),
                ('website', models.CharField(blank=b'user@example.com', max_length=50)),
                ('phonenumber', models.CharField(default=b'999-999-9999', max_length=13)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MusicianUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[(b'Musician', b'Musician'), (b'Venue', b'Venue')], max_length=8)),
                ('genre', models.CharField(blank=True, max_length=30)),
                ('available', models.CharField(blank=True, choices=[(b'LFG', b'Looking For Gig'), (b'AB', b'Already Booked')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VenueUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[(b'Musician', b'Musician'), (b'Venue', b'Venue')], max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
