# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20161201_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuserprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='musicianuserprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='musicianuserprofile',
            name='location',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='musicianuserprofile',
            name='phonenumber',
            field=models.CharField(default=b'999-999-9999', max_length=13),
        ),
        migrations.AddField(
            model_name='musicianuserprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='musicianuserprofile',
            name='type_user',
            field=models.CharField(choices=[(b'Musician', b'Musician'), (b'Venue', b'Venue')], default=b'Musician', max_length=20),
        ),
        migrations.AddField(
            model_name='musicianuserprofile',
            name='website',
            field=models.CharField(blank=b'user@example.com', max_length=50),
        ),
        migrations.AddField(
            model_name='venueuserprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='venueuserprofile',
            name='location',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='venueuserprofile',
            name='phonenumber',
            field=models.CharField(default=b'999-999-9999', max_length=13),
        ),
        migrations.AddField(
            model_name='venueuserprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='venueuserprofile',
            name='type_user',
            field=models.CharField(choices=[(b'Musician', b'Musician'), (b'Venue', b'Venue')], default=b'Venue', max_length=20),
        ),
        migrations.AddField(
            model_name='venueuserprofile',
            name='website',
            field=models.CharField(blank=b'user@example.com', max_length=50),
        ),
        migrations.DeleteModel(
            name='BaseUserProfile',
        ),
    ]
