# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20161201_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicianuserprofile',
            name='profile_type',
        ),
        migrations.RemoveField(
            model_name='venueuserprofile',
            name='profile_type',
        ),
    ]
