# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20161204_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venueuserprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='available',
            field=models.CharField(blank=True, choices=[('Looking For Gig', 'Looking For Gig'), ('Already Booked', 'Already Booked')], max_length=20),
        ),
        migrations.DeleteModel(
            name='VenueUserProfile',
        ),
    ]
