# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20161204_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='genre',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
