# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20161109_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='job_posting',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job_posting',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='job_posting',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='musician_advertisement',
            name='end_availability',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='musician_advertisement',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='musician_advertisement',
            name='start_availability',
            field=models.DateField(),
        ),
    ]
