# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20161203_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician_advertisement',
            name='posting_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
