# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20161204_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Event'),
        ),
    ]
