# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_auto_20161204_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventapplication',
            old_name='application_event',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='eventapplication',
            old_name='user',
            new_name='user_who_applied',
        ),
    ]
